import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import Header from "@/components/includes/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Leadvent Group",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				{/* Bootstrap CSS */}

				<link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
				<link rel="stylesheet" href="/assets/css/animate.css" />
				<link rel="stylesheet" href="/assets/css/colorbox.css" />
				<link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
				<link rel="stylesheet" href="/assets/css/owl.theme.default.min.css" />
				<link rel="stylesheet" href="/assets/css/style.css" />
				<link rel="stylesheet" href="/assets/css/responsive.css" />
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<Header />
				{children}

				{/* Bootstrap JS */}
				<Script src="/assets/js/jquery.js" />
				<Script src="/assets/js/bootstrap.min.js" />
				<Script src="/assets/js/jquery.colorbox.js" />
				<Script src="/assets/js/smoothscroll.js" />
				{/* <Script src="/assets/js/common.js" /> */}
				<Script src="/assets/js/owl.carousel.min.js" />
			</body>
		</html>
	);
}
